In [1]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense
from tensorflow.python.keras.layers import deserialize, serialize
from tensorflow.python.keras.saving import saving_utils

In [2]:
def unpack(model, training_config, weights):
    restored_model = deserialize(model)
    if training_config is not None:
        restored_model.compile(
            **saving_utils.compile_args_from_training_config(
                training_config
            )
        )
    restored_model.set_weights(weights)
    return restored_model

# Hotfix function
def make_keras_picklable():

    def __reduce__(self):
        model_metadata = saving_utils.model_metadata(self)
        training_config = model_metadata.get("training_config", None)
        model = serialize(self)
        weights = self.get_weights()
        return (unpack, (model, training_config, weights))

    cls = Model
    cls.__reduce__ = __reduce__

# Run the function
make_keras_picklable()


In [3]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv("Downloads/Admission_Predict_Ver1.1.csv")

In [5]:
df.drop(columns = ['Serial No.'],inplace = True)

In [6]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
model = Sequential()

model.add(Dense(7,activation = 'relu',input_dim = 7))
model.add(Dense(7,activation = 'relu'))
model.add(Dense(1,activation='linear'))

In [10]:
model.compile(loss = 'mean_squared_error',optimizer = 'Adam')

In [11]:
model.fit(X_train_scaled,y_train,epochs = 100,validation_split = 0.2)

Epoch 1/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3269 - val_loss: 0.3083
Epoch 2/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2433 - val_loss: 0.2349
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1952 - val_loss: 0.1962
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1704 - val_loss: 0.1745
Epoch 5/100
10/10 [==============================] - 0s 1ms/step - loss: 0.1548 - val_loss: 0.1563
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1382 - val_loss: 0.1386
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1224 - val_loss: 0.1198
Epoch 8/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1056 - val_loss: 0.0994
Epoch 9/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0880 - val_loss: 0.0786
Epoch 10/100
10/10 [==============================] - 0s 878us/step - loss: 0.0693 - val_loss: 0.0566
Epoch 

Epoch 83/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0048 - val_loss: 0.0051
Epoch 84/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0047 - val_loss: 0.0051
Epoch 85/100
10/10 [==============================] - 0s 992us/step - loss: 0.0047 - val_loss: 0.0051
Epoch 86/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0047 - val_loss: 0.0050
Epoch 87/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0047 - val_loss: 0.0050
Epoch 88/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0047 - val_loss: 0.0050
Epoch 89/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0046 - val_loss: 0.0050
Epoch 90/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0047 - val_loss: 0.0049
Epoch 91/100
10/10 [==============================] - 0s 896us/step - loss: 0.0046 - val_loss: 0.0050
Epoch 92/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0046 - val_loss: 0.0

In [12]:
import pickle
with open('gradpred.pkl', 'wb') as f:
    pickle.dump(model, f)

In [13]:
pickled_model = pickle.load(open('gradpred.pkl', 'rb'))
pickled_model.predict(X_test_scaled)

array([[0.64887375],
       [0.65486324],
       [1.0029998 ],
       [0.68328404],
       [0.8085306 ],
       [0.65291125],
       [0.74210113],
       [0.75404704],
       [0.7557533 ],
       [0.6477046 ],
       [0.6893057 ],
       [0.68884724],
       [0.8431833 ],
       [0.8234815 ],
       [0.7444262 ],
       [0.85462695],
       [0.6197678 ],
       [0.73470026],
       [0.8937357 ],
       [0.69379014],
       [0.59956497],
       [0.72500265],
       [0.84325534],
       [0.7631077 ],
       [0.8290473 ],
       [0.61025816],
       [0.94676965],
       [0.63940614],
       [0.82368344],
       [0.65277725],
       [0.6326701 ],
       [0.7799405 ],
       [0.5841362 ],
       [0.8919296 ],
       [0.57257366],
       [0.79172856],
       [0.7237785 ],
       [0.6524678 ],
       [0.66932786],
       [0.90260655],
       [0.5469816 ],
       [0.643248  ],
       [0.82051206],
       [0.9469512 ],
       [0.76313615],
       [0.49272537],
       [0.68941146],
       [0.651

In [14]:
X_test_scaled

array([[ 0.46      ,  0.5       ,  0.25      ,  0.375     ,  0.14285714,
         0.5224359 ,  0.        ],
       [ 0.44      ,  0.53571429,  0.5       ,  0.5       ,  0.42857143,
         0.53205128,  1.        ],
       [ 0.98      ,  0.96428571,  1.        ,  0.875     ,  0.71428571,
         0.92948718,  0.        ],
       [ 0.52      ,  0.53571429,  0.25      ,  0.625     ,  0.57142857,
         0.58974359,  1.        ],
       [ 0.7       ,  0.64285714,  0.75      ,  0.875     ,  0.71428571,
         0.69230769,  1.        ],
       [ 0.42      ,  0.32142857,  0.25      ,  0.375     ,  0.57142857,
         0.49358974,  1.        ],
       [ 0.6       ,  0.42857143,  0.5       ,  0.5       ,  0.57142857,
         0.62179487,  1.        ],
       [ 0.74      ,  0.39285714,  0.5       ,  0.75      ,  0.71428571,
         0.48076923,  1.        ],
       [ 0.62      ,  0.67857143,  0.5       ,  0.625     ,  0.71428571,
         0.65064103,  1.        ],
       [ 0.56      ,  0.5   

In [16]:
obs = [[320,100,3,4,4,9.36,0]]
obs_scaled = scaler.transform(obs)

pickled_model.predict(obs_scaled)

array([[0.81218106]], dtype=float32)